#!/usr/bin/env bash
#script that installs nginx on the local server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start

