#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
#Configure HAproxy so that it send traffic to web-01 and web-02
#Make sure that HAproxy can be managed via an init script

sudo apt-get update
sudo apt-get install haproxy -y


sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null << EOT
frontend http-in
	bind *:80
	default_backend annette_servers


backend annette_servers
	balance roundrobin
	server 134447-web-01 52.87.232.99:80 check
	server 134447-web-02 34.204.81.158:80 check
EOT

#start the server
sudo /etc/init.d/haproxy start

#the server should start on boot
sudo update-rc.d haproxy defaults

sudo /etc/init.d/haproxy reload
