#!/usr/bin/env bash
#debugging nginx not listening in port 80

netstat -ntlp

rm etc/nginx/sites-enabled/default
sudo ln -s etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
